### ISSUE TITLE
TypeError: (0 , _nanoid.nanoid) is not a function

### ISSUE THREAD

**Issue by davidNHK** [ai/nanoid#205]
I trying upgrade nanoid from 2.x to 3.x in CRA environment

The export value from `nanoid` is always undefined 

And i got error when running below jest test

```js
import { nanoid } from 'nanoid';
it('Should work', () => {
  console.log('nanoid is ', nanoid);
  const genId = nanoid();
  expect(() => genId()).not.toThrow();
});
```

Console message
```js
console.log src/services/spotify/auth/__tests__/authorize.test.ts:14
    nanoid is  undefined
TypeError: (0 , _nanoid.nanoid) is not a function

```

Also i try below test

```js
import * as nanoid from 'nanoid';

it('Should work', () => {
  console.log('nanoid is ', nanoid);
  const genId = nanoid.nanoid();
  expect(() => genId()).not.toThrow();
});
```

Console message
```js
  console.log src/services/spotify/auth/__tests__/authorize.test.ts:14
    nanoid is  { default: 'index.cjs' }
TypeError: nanoid.nanoid is not a function
```

**Comment by davidNHK** [comment]
https://github.com/davidNHK/spotify-music-player/blob/development/src/services/spotify/auth/authorize.ts

Source reference

**Comment by TrySound** [comment]
Maybe CRA has some cache? Did you try to rerun it after installing new version?

**Comment by TrySound** [comment]
Hm.. this is unexpected `nanoid is  { default: 'index.cjs' }`. v2 does not have this.

**Comment by TrySound** [comment]
Perhaps the problem comes from the fact that CRA does not support .cjs extension.

**Comment by ai** [comment]
> Perhaps the problem comes from the fact that CRA does not support .cjs extension.

CRA should use ESM or even `index.browser.js`.

Does CRA still use a webpack?

**Comment by TrySound** [comment]
Got it. It's loaded as path with file loader 🤦‍♂ 

https://github.com/facebook/create-react-app/blob/edc671eeea6b7d26ac3f1eb2050e50f75cf9ad5d/packages/react-scripts/config/webpack.config.js#L544-L549

**Comment by ai** [comment]
Fixing `.cjs` loading will not fix the problem.

`index.browser.js` should be loaded according to `package.browser`

**Comment by TrySound** [comment]
Perhaps specified extensions prevents browser field lookup
https://github.com/facebook/create-react-app/blob/edc671eeea6b7d26ac3f1eb2050e50f75cf9ad5d/packages/react-scripts/config/paths.js#L32-L44

**Comment by ai** [comment]
@davidNHK can you open `node_modules/nanoid`, rename `index.browser.js` to `index.web.js` and replace file names in `package.json`→`browser`?

If `web.js` works in CRA, I will change the name in `dual-publish`.

**Comment by ai** [comment]
@davidNHK I cloned [your project](https://github.com/davidNHK/spotify-music-player), updated Nano ID by `yarn upgrade-interactive --latest`, replaced `import nanoid from` to `import { nanoid } from` and everything starts to work.

In your [pull request](https://github.com/davidNHK/spotify-music-player/pull/176/files), you didn’t replace `import nanoid from` import { nanoid } from`.

Can you try to do it again with updating imports according to the [migration guide](https://github.com/ai/nanoid/releases/tag/3.0.0). If you will have any problem, just give me a link to git branch to reproduce the error.

**Comment by davidNHK** [comment]
> @davidNHK I cloned [your project](https://github.com/davidNHK/spotify-music-player), updated Nano ID by `yarn upgrade-interactive --latest`, replaced `import nanoid from` to `import { nanoid } from` and everything starts to work.
> 
> In your [pull request](https://github.com/davidNHK/spotify-music-player/pull/176/files), you didn’t replace `import nanoid from` import { nanoid } from`.
> 
> Can you try to do it again with updating imports according to the [migration guide](https://github.com/ai/nanoid/releases/tag/3.0.0). If you will have any problem, just give me a link to git branch to reproduce the error.

@ai 

I attempt follow the [migration guide](https://github.com/ai/nanoid/releases/tag/3.0.0) 

But problem still exist, [PR here](https://github.com/davidNHK/spotify-music-player/pull/195)

P.S. i also attempt change index.browser to index.web and no luck

**Comment by baeharam** [comment]
Same issue here

**Comment by ai** [comment]
@davidNHK everything works in the web, problem realted with Create React App test runner.

**Comment by ai** [comment]
I found the problem in the CRA jest config generator. Wait for a second, I will create pull request to CRA.

**Comment by ai** [comment]
I created pull request https://github.com/facebook/create-react-app/pull/8768

Please add 👍 if you want to merge it quicker

**Comment by ai** [comment]
I also added note about CRA to [docs](https://github.com/ai/nanoid#create-react-app) and [migration guide](https://github.com/ai/nanoid/releases/tag/3.0.0)

**Comment by ai** [comment]
My PR was accepting. Now we need to wait a few days for the new CRA release.

**Comment by sandrocsimas** [comment]
In node.js this is not working:
````
const nanoid = require('nanoid');
nanoid();
````
This works:
````
const {nanoid} = require('nanoid');
nanoid();
````

**Comment by tareqdayya** [comment]
Any news on this?
For some reason, this problem occurs only when i'm mocking the module globally (inside  __mocks__/nanoid.ts) like this:
`export default {
  nanoid: () => '123456789012',
};`
But not when i mock it inside individual test suites like this:
`jest.mock('nanoid', () => ({
  nanoid: () => '123456789012',
}));`

**Comment by ai** [comment]
@tareqdayya Create React App maintainers accepted my PR but still do not release it. Feel free to create an issue in [their repo](https://github.com/facebook/create-react-app) and ask for release.

I can’t help here. Ask CRA maintainers about releasing the fix,

**Comment by towry** [comment]
```diff
-    "nanoid": "^3.1.10",
+    "nanoid": "^3.0.2",
```

Downgrade the version from `3.1.10` to `3.0.2` fixed this issue !!

**Comment by longpos222** [comment]
> In node.js this is not working:
> 
> ```
> const nanoid = require('nanoid');
> nanoid();
> ```
> 
> This works:
> 
> ```
> const {nanoid} = require('nanoid');
> nanoid();
> ```

I face the same issue and this one work for my case.

Thanks for saving 1 hour.

**Comment by AntonioLobo** [comment]
I'm facing the same problem when using react testing library
`TypeError: (0 , _nanoid.nanoid) is not a function`

using nanoid version ^3.1.12

**Comment by ai** [comment]
@AntonioLobo do you use Create React App?

I sent the fix to CRA, but they are still not released it.

**Comment by gsdeveloper** [comment]
Updated Create React App to 4.0.0 and it's fixed

**Comment by gsdeveloper** [comment]
Update: solved again an entire different app by updating CRA to 4.0.0. Seems the solution for who is using:
- Create react app
- React testing Library

**Comment by tsAppDevelopment** [comment]
I'm having the same issue when running on [Code Sandbox](https://codesandbox.io/s/heuristic-frost-o54cy?file=/src/App.tsx). It seems to work fine below version 3.1.17 of nanoid. Is this related, or could it be an issue with Code Sandbox?

**Comment by lavrton** [comment]
Just had the same issue on code sandbox too. I am not sure where to look at. 

The demo from @tsAppDevelopment works ok with `3.1.16` and not ok from version `3.1.17`

**Comment by AvraamMavridis** [comment]
For anyone that is still facing the issue. ESM can’t import named CJS exports unless CJS scripts execute out of order

So you can do this:

```
import nanoid from 'nanoid'
```

but you can't do this:

```
import { nanoid } from 'nanoid'
```

That’s because CJS scripts compute their named exports as they execute, whereas ESM’s named exports must be computed during the parsing phase.

A workaround is

```
import _nanoid from 'nanoid'
const { nanoid } = _nanoid
```
