### ISSUE TITLE
TypeError: nanoid is not a function when using react native web and styled components

### ISSUE THREAD

**Issue by eshankvaish** [ai/nanoid#429]
This seems to be related to https://github.com/postcss/postcss/issues/1727. So I was using react native on the web along with styled-components that use postcss. While everything was working as expected on Android and iOS but each time I tried using the app on the web, I kept on getting the error `nanoid is not a function` at https://github.com/postcss/postcss/blob/main/lib/input.js#L58. Upon debugging, I figured out that the nanoid version `3.3.6` was causing the issue due to breaking CJS support probably as mentioned in https://github.com/ai/nanoid/issues/422 as well. Upon adding the following resolutions to my package.json file, the error was finally resolved:

```json
"resolutions": {
    "**/nanoid": "3.3.5"
}
```

Here is the link to a sample repository to reproduce the issue: https://github.com/eshankvaish/nanoid-issue and how I fixed the issue: https://github.com/eshankvaish/nanoid-issue/pull/1.

![image](https://github.com/ai/nanoid/assets/48060426/5a5ec251-4e92-40bb-b268-412b864246bb)

**Comment by ai** [comment]
It looks like a bug in package manager.

PostCSS already requires only `3.x` branch. Package manager should not provide `4.x` for PostCSS.

**Comment by eshankvaish** [comment]
I was actually mentioning about `3.x` branch only and here it points out to `^3.3.6` specifically: https://github.com/postcss/postcss/blob/main/package.json#L82

**Comment by ai** [comment]
I got the reason (sorry, I missed with https://github.com/postcss/postcss/issues/1727 where we had broken lock file)! 3.3.5 was broken. You just need to update to 3.3.6.

**Comment by eshankvaish** [comment]
But the issue seems to be caused on 3.3.6 itself and working fine on 3.3.5 if you check the attached repo for reproduction along with the lock file in the same repo. I guess there was some breaking change in the 3.3.6 release as compared to 3.3.5. I noticed that when I was using 3.3.6, I was getting the link to the file instead of the object exposed by it when using:
```js
const { nanoid } = require('nanoid/no-secure')
```

I tried finding the diff between the 3.3.5 and 3.3.6 but couldn't find the later tag 🧐

**Comment by eshankvaish** [comment]
Also just to mention again, I had to downgrade to 3.3.5 to make the code work.

**Comment by ai** [comment]
Very strange. The issue of 3.3.5 that it was released without dual CJS+ESM support (only CJS files).

Maybe you have some issues with builing ESM for RN?

**Comment by ai** [comment]
Unfortunatelly, I can’t help you in debug since I have no RN and iOS dev tools.

The best way to check content is Code tab

* https://www.npmjs.com/package/nanoid/v/3.3.6?activeTab=code
* https://www.npmjs.com/package/nanoid/v/3.3.5?activeTab=code

**Comment by eshankvaish** [comment]
> Very strange. The issue of 3.3.5 that it was released without dual CJS+ESM support (only CJS files), which we do on publish state.
> 
> Maybe you have some issues with building ESM for RN?

This maybe possible, I'll check and update here by tomorrow with an update.

**Comment by eshankvaish** [comment]
> Unfortunatelly, I can’t help you in debug since I have no RN and iOS dev tools.
> 
> The best way to check content is Code tab
> 
> * https://www.npmjs.com/package/nanoid/v/3.3.6?activeTab=code
> * https://www.npmjs.com/package/nanoid/v/3.3.5?activeTab=code

Oh, got it. I'll try to figure out on my own then. Just FYI, the RN repo I shared uses expo internally so you can run the app on web to the least with couple of yarn commands if you want but anyways thanks for providing the details.

**Comment by eshankvaish** [comment]
So just in order to confirm the working, I imported the `nanoid` using the import statement side by side with the existing require statement as in the attached screenshot:
![image](https://github.com/ai/nanoid/assets/48060426/23860f6c-5a81-4329-b298-8c4ffc9ffd26)

I noticed that while the import statement was working fine, the regular import didn't work.

![image](https://github.com/ai/nanoid/assets/48060426/051c68fc-446b-47eb-834e-03e168e08021)

I'll try further to figure out if my setup is unable to bundle the ESM because the same set up of styled components works with a React based app out of the box.

**Comment by dev-willyy** [comment]
This doesn't seem to work at the moment. I have added 

> "resolutions": {
>     "**/nanoid": "3.3.5"
> }

into the package.json file of my root directory, yet I still get this error. It's been almost a week now, and I'm yet to get a fix. I'll be glad if anyone could be of help

**Comment by OoYomguioO** [comment]
Hello,
Can I find out what the application's dependencies are?
I think it's an incompatibility.
In my case it works with :

`  "dependencies": {
    "expo": "~49.0.11",
    "expo-constants": "~14.4.2",
    "expo-status-bar": "~1.6.0",
    "formik": "^2.4.5",
    "nanoid": "3.0.0",
    "react": "18.2.0",
    "react-devtools": "^4.28.0",
    "react-dom": "18.2.0",
    "react-native": "0.72.4",
    "react-native-web": "~0.19.6",
    "styled-components": "^6.0.8",
    "@expo/webpack-config": "^19.0.0"
  },`

**Comment by neeraj500** [comment]
I am facing the same issue, were you able to resolve it? @dev-willyy

**Comment by neeraj500** [comment]
I fixed the issue now using patch-package. 
Just use the library and make changes to your input.js present inside, 

 `node_modules -> styled-components ->node_modules ->postcss -> input.js.`

Inside input.js where it is importing nanoid from nanoid/no-secure, change it with nanoid.

Next step, patch the file and it doesn't give the same error again.

NOTE: If this works and you install any other library, you'll probably face this issue again as installing anything will revert the changes.

**Comment by ai** [comment]
@neeraj500 there is something different wrong in your system. I am removing this suggestion because it is dangerous (you should not use `nanoid` instead of `nanoid/non-secure`).

Open another issue, since you have a non-relevant bug.

**Comment by ai** [comment]
Use `resolutions` carefully, it could lead to unexpected behavior of libraries.

**Comment by eusouoviana** [comment]
Still happening.

**Comment by ai** [comment]
Should not be an issue in new v5
